/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import courseenrolmentsystem.Dboperation6;
import courseenrolmentsystem.paymentdetailsdb;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author U s E r ™
 */
public class Pay_semester extends javax.swing.JInternalFrame {
    Dboperation6 db6 = new Dboperation6();
    String url = "jdbc:mysql://localhost:3306/nsbm";
    String username = "root";
    String password = "";
    Connection con = null;
    Statement pst = null;
    ResultSet rs = null;
    
    /**
     * Creates new form student_manage
     */
    public Pay_semester() {
        super("Pay_semester");
        initComponents();
        try{
            con = (Connection) DriverManager.getConnection(url, username, password);
        }catch(Exception e)
        {
        }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtregno1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jy1 = new javax.swing.JComboBox();
        js1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtsubc1 = new javax.swing.JTextField();
        txtsubc2 = new javax.swing.JTextField();
        txtsubc3 = new javax.swing.JTextField();
        txtsubc4 = new javax.swing.JTextField();
        txtsubc5 = new javax.swing.JTextField();
        txtsubc6 = new javax.swing.JTextField();
        txtsub1 = new javax.swing.JTextField();
        txtsub2 = new javax.swing.JTextField();
        txtsub3 = new javax.swing.JTextField();
        txtsub4 = new javax.swing.JTextField();
        txtsub5 = new javax.swing.JTextField();
        txtsub6 = new javax.swing.JTextField();
        txtfee1 = new javax.swing.JTextField();
        txtfee2 = new javax.swing.JTextField();
        txtfee3 = new javax.swing.JTextField();
        txtfee4 = new javax.swing.JTextField();
        txtfee5 = new javax.swing.JTextField();
        txtfee6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txttot1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtregno2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jy2 = new javax.swing.JComboBox();
        js2 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtsubc7 = new javax.swing.JTextField();
        txtsubc8 = new javax.swing.JTextField();
        txtsubc9 = new javax.swing.JTextField();
        txtsubc10 = new javax.swing.JTextField();
        txtsubc11 = new javax.swing.JTextField();
        txtsubc12 = new javax.swing.JTextField();
        txtsub7 = new javax.swing.JTextField();
        txtsub8 = new javax.swing.JTextField();
        txtsub9 = new javax.swing.JTextField();
        txtsub10 = new javax.swing.JTextField();
        txtsub11 = new javax.swing.JTextField();
        txtsub12 = new javax.swing.JTextField();
        txtfee7 = new javax.swing.JTextField();
        txtfee8 = new javax.swing.JTextField();
        txtfee9 = new javax.swing.JTextField();
        txtfee10 = new javax.swing.JTextField();
        txtfee11 = new javax.swing.JTextField();
        txtfee12 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txttot2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("Registration no");

        jLabel2.setText("Year");

        jLabel3.setText("Semester");

        jy1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));

        js1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));

        jLabel4.setText("Subject code");

        jLabel5.setText("Subject");

        jLabel6.setText("Fee");

        txtsubc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubc4ActionPerformed(evt);
            }
        });

        txtsubc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubc5ActionPerformed(evt);
            }
        });

        txtsubc6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubc6ActionPerformed(evt);
            }
        });

        txtsub4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsub4ActionPerformed(evt);
            }
        });

        txtsub5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsub5ActionPerformed(evt);
            }
        });

        txtsub6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsub6ActionPerformed(evt);
            }
        });

        txtfee2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfee2ActionPerformed(evt);
            }
        });

        txtfee3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfee3ActionPerformed(evt);
            }
        });

        txtfee4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfee4ActionPerformed(evt);
            }
        });

        txtfee6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfee6ActionPerformed(evt);
            }
        });

        jLabel7.setText("Total payment");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton11.setText("Search");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Search");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Search");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("Search");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("Search");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("Search");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtregno1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(js1, javax.swing.GroupLayout.Alignment.LEADING, 0, 74, Short.MAX_VALUE)
                                .addComponent(jy1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(115, 115, 115)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtsubc5, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                    .addComponent(txtsubc6))
                                .addGap(67, 67, 67)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtsub6, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addComponent(txtsub5)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtsubc1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                    .addComponent(txtsubc2)
                                    .addComponent(txtsubc3)
                                    .addComponent(txtsubc4))
                                .addGap(67, 67, 67)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtsub3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsub1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsub4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsub2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfee1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                            .addComponent(txtfee2)
                            .addComponent(txtfee3)
                            .addComponent(txtfee4)
                            .addComponent(txtfee5)
                            .addComponent(txtfee6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton15)
                                    .addComponent(jButton11)
                                    .addComponent(jButton13)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton16)
                                        .addGap(57, 57, 57)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton14)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton12)
                                        .addGap(57, 57, 57)
                                        .addComponent(txttot1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 28, Short.MAX_VALUE)))))
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(145, 145, 145))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtregno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(js1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsubc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsub1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfee1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsubc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsub2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfee2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsubc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsub3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfee3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsubc4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsub4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfee4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton14))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsubc5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsub5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfee5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton15)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(199, 199, 199)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtsub6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfee6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsubc6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton16)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txttot1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(150, 150, 150)
                                .addComponent(jButton1)
                                .addGap(11, 11, 11)))))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Postgraduate", jPanel1);

        jLabel8.setText("Registration no");

        jLabel9.setText("Year");

        jLabel10.setText("Semester");

        jy2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));

        js2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));

        jLabel11.setText("Subject code");

        jLabel12.setText("Subject");

        jLabel13.setText("Fee");

        txtsubc10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubc10ActionPerformed(evt);
            }
        });

        txtsubc11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubc11ActionPerformed(evt);
            }
        });

        txtsubc12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubc12ActionPerformed(evt);
            }
        });

        txtsub10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsub10ActionPerformed(evt);
            }
        });

        txtsub11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsub11ActionPerformed(evt);
            }
        });

        txtsub12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsub12ActionPerformed(evt);
            }
        });

        txtfee9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfee9ActionPerformed(evt);
            }
        });

        txtfee10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfee10ActionPerformed(evt);
            }
        });

        txtfee12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfee12ActionPerformed(evt);
            }
        });

        jLabel14.setText("Total payment");

        txttot2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttot2ActionPerformed(evt);
            }
        });

        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Select");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Select");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Select");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Select");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Select");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Select");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtregno2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(js2, javax.swing.GroupLayout.Alignment.LEADING, 0, 74, Short.MAX_VALUE)
                                    .addComponent(jy2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                                .addComponent(jButton4)
                                .addGap(76, 76, 76)))
                        .addGap(59, 59, 59))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(115, 115, 115)
                                .addComponent(jLabel12))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtsubc11, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                    .addComponent(txtsubc12))
                                .addGap(67, 67, 67)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtsub12, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                    .addComponent(txtsub11)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtsubc7, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                    .addComponent(txtsubc8)
                                    .addComponent(txtsubc9)
                                    .addComponent(txtsubc10))
                                .addGap(67, 67, 67)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtsub9, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsub7, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsub10, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsub8, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfee7, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                            .addComponent(txtfee8)
                            .addComponent(txtfee9)
                            .addComponent(txtfee10)
                            .addComponent(txtfee11)
                            .addComponent(txtfee12))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton6)
                                .addGap(35, 35, 35)
                                .addComponent(txttot2))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton8)
                                    .addComponent(jButton7)
                                    .addComponent(jButton10)
                                    .addComponent(jButton9))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtregno2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(js2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsubc7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsub7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfee7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsubc8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsub8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfee8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsubc9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsub9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfee9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsubc10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsub10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfee10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsubc11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsub11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfee11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(txttot2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtsub12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfee12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsubc12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton5)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Undergraduate", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsubc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubc5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubc5ActionPerformed

    private void txtsubc6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubc6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubc6ActionPerformed

    private void txtsubc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubc4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubc4ActionPerformed

    private void txtsub5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsub5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsub5ActionPerformed

    private void txtsub6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsub6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsub6ActionPerformed

    private void txtsub4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsub4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsub4ActionPerformed

    private void txtfee3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfee3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfee3ActionPerformed

    private void txtfee4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfee4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfee4ActionPerformed

    private void txtfee6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfee6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfee6ActionPerformed

    private void txtsubc10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubc10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubc10ActionPerformed

    private void txtsubc11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubc11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubc11ActionPerformed

    private void txtsubc12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubc12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubc12ActionPerformed

    private void txtsub10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsub10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsub10ActionPerformed

    private void txtsub11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsub11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsub11ActionPerformed

    private void txtsub12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsub12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsub12ActionPerformed

    private void txtfee9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfee9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfee9ActionPerformed

    private void txtfee10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfee10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfee10ActionPerformed

    private void txtfee12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfee12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfee12ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            pst = con.createStatement();
             
            String reg_no = txtregno1.getText();
            String year = jy1.getSelectedItem().toString();
            String sem = js1.getSelectedItem().toString();
            String sql = "SELECT Subject_code_1,Subject_1,Subject_code_2,Subject_2,Subject_code_3,Subject_3,Subject_code_4,Subject_4,Subject_code_5,Subject_5,Subject_code_6,Subject_6 FROM postgraduate_select_subjects WHERE Reg_no= '"+reg_no+"' and Year='"+year+"' and Semester='"+sem+"'";
            
            rs = pst.executeQuery(sql);
            
            if(rs.next()){
                txtsubc1.setText(rs.getString("Subject_code_1"));
                txtsub1.setText(rs.getString("Subject_1"));
                txtsubc2.setText(rs.getString("Subject_code_2"));
                txtsub2.setText(rs.getString("Subject_2"));
                txtsubc3.setText(rs.getString("Subject_code_3"));
                txtsub3.setText(rs.getString("Subject_3"));
                txtsubc4.setText(rs.getString("Subject_code_4"));
                txtsub4.setText(rs.getString("Subject_4"));
                txtsubc5.setText(rs.getString("Subject_code_5"));
                txtsub5.setText(rs.getString("Subject_5"));
                txtsubc6.setText(rs.getString("Subject_code_6"));
                txtsub6.setText(rs.getString("Subject_6"));
                                
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Student not found");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

                                          

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            pst = con.createStatement();
             
            String reg_no = txtregno2.getText();
            String year = jy2.getSelectedItem().toString();
            String sem = js2.getSelectedItem().toString();
            String sql = "SELECT Subject_code_1,Subject_1,Subject_code_2,Subject_2,Subject_code_3,Subject_3,Subject_code_4,Subject_4,Subject_code_5,Subject_5,Subject_code_6,Subject_6 FROM undergraduate_select_subject WHERE Reg_no= '"+reg_no+"' and Year='"+year+"' and Semester='"+sem+"'";
            
            rs = pst.executeQuery(sql);
            
            if(rs.next()){
                txtsubc7.setText(rs.getString("Subject_code_1"));
                txtsub7.setText(rs.getString("Subject_1"));
                txtsubc8.setText(rs.getString("Subject_code_2"));
                txtsub8.setText(rs.getString("Subject_2"));
                txtsubc9.setText(rs.getString("Subject_code_3"));
                txtsub9.setText(rs.getString("Subject_3"));
                txtsubc10.setText(rs.getString("Subject_code_4"));
                txtsub10.setText(rs.getString("Subject_4"));
                txtsubc11.setText(rs.getString("Subject_code_5"));
                txtsub11.setText(rs.getString("Subject_5"));
                txtsubc12.setText(rs.getString("Subject_code_6"));
                txtsub12.setText(rs.getString("Subject_6"));
                                
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Subjects not found");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txttot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttot2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttot2ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        try{
            pst = con.createStatement();
             
            int subcode = new Integer(txtsubc1.getText()).intValue();
            String sql = "SELECT Fee FROM postgraduate_subjects WHERE Subject_code = '"+subcode+"' ";
            
            rs = pst.executeQuery(sql);
            
            if(rs.next()){
                txtfee1.setText(rs.getString("Fee"));            
            }
            else{
                JOptionPane.showMessageDialog(null, "Fee not found");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

                                          

    
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        try{
            pst = con.createStatement();
             
            int subcode = new Integer(txtsubc2.getText()).intValue();
            String sql = "SELECT Fee FROM postgraduate_subjects WHERE Subject_code = '"+subcode+"' ";
            
            rs = pst.executeQuery(sql);
            
            if(rs.next()){
                txtfee2.setText(rs.getString("Fee"));            
            }
            else{
                JOptionPane.showMessageDialog(null, "Fee not found");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        try{
            pst = con.createStatement();
             
            int subcode = new Integer(txtsubc3.getText()).intValue();
            String sql = "SELECT Fee FROM postgraduate_subjects WHERE Subject_code = '"+subcode+"' ";
            
            rs = pst.executeQuery(sql);
            
            if(rs.next()){
                txtfee3.setText(rs.getString("Fee"));            
            }
            else{
                JOptionPane.showMessageDialog(null, "Fee not found");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        try{
            pst = con.createStatement();
             
            int subcode = new Integer(txtsubc4.getText()).intValue();
            String sql = "SELECT Fee FROM postgraduate_subjects WHERE Subject_code = '"+subcode+"' ";
            
            rs = pst.executeQuery(sql);
            
            if(rs.next()){
                txtfee4.setText(rs.getString("Fee"));            
            }
            else{
                JOptionPane.showMessageDialog(null, "Fee not found");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        try{
            pst = con.createStatement();
             
            int subcode = new Integer(txtsubc5.getText()).intValue();
            String sql = "SELECT Fee FROM postgraduate_subjects WHERE Subject_code = '"+subcode+"' ";
            
            rs = pst.executeQuery(sql);
            
            if(rs.next()){
                txtfee5.setText(rs.getString("Fee"));            
            }
            else{
                JOptionPane.showMessageDialog(null, "Fee not found");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        try{
            pst = con.createStatement();
             
            int subcode = new Integer(txtsubc6.getText()).intValue();
            String sql = "SELECT Fee FROM postgraduate_subjects WHERE Subject_code = '"+subcode+"' ";
            
            rs = pst.executeQuery(sql);
            
            if(rs.next()){
                txtfee6.setText(rs.getString("Fee"));            
            }
            else{
                JOptionPane.showMessageDialog(null, "Fee not found");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
      try{
            pst = con.createStatement();
             
            int subcode = new Integer(txtsubc7.getText()).intValue();
            String sql = "SELECT Fee FROM undergraduate_subjects WHERE Subject_code = '"+subcode+"' ";
            
            rs = pst.executeQuery(sql);
            
            if(rs.next()){
                txtfee7.setText(rs.getString("Fee"));            
            }
            else{
                JOptionPane.showMessageDialog(null, "Fee not found");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try{
            pst = con.createStatement();
             
            int subcode = new Integer(txtsubc8.getText()).intValue();
            String sql = "SELECT Fee FROM undergraduate_subjects WHERE Subject_code = '"+subcode+"' ";
            
            rs = pst.executeQuery(sql);
            
            if(rs.next()){
                txtfee8.setText(rs.getString("Fee"));            
            }
            else{
                JOptionPane.showMessageDialog(null, "Fee not found");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try{
            pst = con.createStatement();
             
            int subcode = new Integer(txtsubc9.getText()).intValue();
            String sql = "SELECT Fee FROM undergraduate_subjects WHERE Subject_code = '"+subcode+"' ";
            
            rs = pst.executeQuery(sql);
            
            if(rs.next()){
                txtfee9.setText(rs.getString("Fee"));            
            }
            else{
                JOptionPane.showMessageDialog(null, "Fee not found");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
   
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        try{
            pst = con.createStatement();
             
            int subcode = new Integer(txtsubc10.getText()).intValue();
            String sql = "SELECT Fee FROM undergraduate_subjects WHERE Subject_code = '"+subcode+"' ";
            
            rs = pst.executeQuery(sql);
            
            if(rs.next()){
                txtfee10.setText(rs.getString("Fee"));            
            }
            else{
                JOptionPane.showMessageDialog(null, "Fee not found");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        try{
            pst = con.createStatement();
             
            int subcode = new Integer(txtsubc11.getText()).intValue();
            String sql = "SELECT Fee FROM undergraduate_subjects WHERE Subject_code = '"+subcode+"' ";
            
            rs = pst.executeQuery(sql);
            
            if(rs.next()){
                txtfee11.setText(rs.getString("Fee"));            
            }
            else{
                JOptionPane.showMessageDialog(null, "Fee not found");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try{
            pst = con.createStatement();
             
            int subcode = new Integer(txtsubc12.getText()).intValue();
            String sql = "SELECT Fee FROM undergraduate_subjects WHERE Subject_code = '"+subcode+"' ";
            
            rs = pst.executeQuery(sql);
            
            if(rs.next()){
                txtfee12.setText(rs.getString("Fee"));            
            }
            else{
                JOptionPane.showMessageDialog(null, "Fee not found");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        paymentdetailsdb pay1 = new paymentdetailsdb();
        
        pay1.setReg_no1(txtregno1.getText().toString());
        pay1.setYear1(jy1.getSelectedItem().toString());
        pay1.setSemester1(js1.getSelectedItem().toString());
        pay1.setSubcode1_1(txtsubc1.getText());
        pay1.setSubcode2_1(txtsubc2.getText());
        pay1.setSubcode3_1(txtsubc3.getText());
        pay1.setSubcode4_1(txtsubc4.getText());
        pay1.setSubcode5_1(txtsubc5.getText());
        pay1.setSubcode6_1(txtsubc6.getText());
        pay1.setFee1_1(txtfee1.getText());
        pay1.setFee1_2(txtfee2.getText());
        pay1.setFee1_3(txtfee3.getText());
        pay1.setFee1_4(txtfee4.getText());
        pay1.setFee1_5(txtfee5.getText());
        pay1.setFee1_6(txtfee6.getText());
        pay1.setTotal_1(txttot1.getText());
              
        
        
        boolean result =db6.addPostgraduatePayment(pay1);
        
        if(result){
            Dboperation6 db6 = new Dboperation6();
            JOptionPane.showMessageDialog(this,"Payment is successful!!");
            clearFields();
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "Oops error occured while inserting!!");
        }
      
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtfee2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfee2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfee2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        paymentdetailsdb pay2 = new paymentdetailsdb();
        
        pay2.setReg_no2(txtregno2.getText().toString());
        pay2.setYear2(jy1.getSelectedItem().toString());
        pay2.setSemester2(js1.getSelectedItem().toString());
        pay2.setSubcode1_2(txtsubc7.getText());
        pay2.setSubcode2_2(txtsubc8.getText());
        pay2.setSubcode3_2(txtsubc9.getText());
        pay2.setSubcode4_2(txtsubc10.getText());
        pay2.setSubcode5_2(txtsubc11.getText());
        pay2.setSubcode6_2(txtsubc12.getText());
        pay2.setFee2_1(txtfee7.getText());
        pay2.setFee2_2(txtfee8.getText());
        pay2.setFee2_3(txtfee9.getText());
        pay2.setFee2_4(txtfee10.getText());
        pay2.setFee2_5(txtfee11.getText());
        pay2.setFee2_6(txtfee12.getText());
        pay2.setTotal_2(txttot2.getText());
              
        
        
        boolean result =db6.addUndergraduatePayment(pay2);
        
        if(result){
            Dboperation6 db6 = new Dboperation6();
            JOptionPane.showMessageDialog(this,"Payment is successful!!");
            clearFields();
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "Oops error occured while inserting!!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    
    void clearFields(){
        txtregno1.setText("");
        txtsubc1.setText("");
        txtsubc2.setText("");
        txtsubc3.setText("");
        txtsubc4.setText("");
        txtsubc5.setText("");
        txtsubc6.setText("");
        txtfee1.setText("");
        txtfee2.setText("");
        txtfee3.setText("");
        txtfee4.setText("");
        txtfee5.setText("");
        txtfee6.setText("");
        txttot1.setText("");
        txtregno2.setText("");
        txtsubc7.setText("");
        txtsubc8.setText("");
        txtsubc9.setText("");
        txtsubc10.setText("");
        txtsubc11.setText("");
        txtsubc12.setText("");
        txtfee7.setText("");
        txtfee8.setText("");
        txtfee9.setText("");
        txtfee10.setText("");
        txtfee11.setText("");
        txtfee12.setText("");
        txttot2.setText("");
        
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox js1;
    private javax.swing.JComboBox js2;
    private javax.swing.JComboBox jy1;
    private javax.swing.JComboBox jy2;
    private javax.swing.JTextField txtfee1;
    private javax.swing.JTextField txtfee10;
    private javax.swing.JTextField txtfee11;
    private javax.swing.JTextField txtfee12;
    private javax.swing.JTextField txtfee2;
    private javax.swing.JTextField txtfee3;
    private javax.swing.JTextField txtfee4;
    private javax.swing.JTextField txtfee5;
    private javax.swing.JTextField txtfee6;
    private javax.swing.JTextField txtfee7;
    private javax.swing.JTextField txtfee8;
    private javax.swing.JTextField txtfee9;
    private javax.swing.JTextField txtregno1;
    private javax.swing.JTextField txtregno2;
    private javax.swing.JTextField txtsub1;
    private javax.swing.JTextField txtsub10;
    private javax.swing.JTextField txtsub11;
    private javax.swing.JTextField txtsub12;
    private javax.swing.JTextField txtsub2;
    private javax.swing.JTextField txtsub3;
    private javax.swing.JTextField txtsub4;
    private javax.swing.JTextField txtsub5;
    private javax.swing.JTextField txtsub6;
    private javax.swing.JTextField txtsub7;
    private javax.swing.JTextField txtsub8;
    private javax.swing.JTextField txtsub9;
    private javax.swing.JTextField txtsubc1;
    private javax.swing.JTextField txtsubc10;
    private javax.swing.JTextField txtsubc11;
    private javax.swing.JTextField txtsubc12;
    private javax.swing.JTextField txtsubc2;
    private javax.swing.JTextField txtsubc3;
    private javax.swing.JTextField txtsubc4;
    private javax.swing.JTextField txtsubc5;
    private javax.swing.JTextField txtsubc6;
    private javax.swing.JTextField txtsubc7;
    private javax.swing.JTextField txtsubc8;
    private javax.swing.JTextField txtsubc9;
    private javax.swing.JTextField txttot1;
    private javax.swing.JTextField txttot2;
    // End of variables declaration//GEN-END:variables
}
